version: "3.8"
services:
  postgres_cadastro:
   container_name: postgres_cadastro_ifood
   image: postgres:12.5
   environment:
    POSTGRES_USER: cadastro
    POSTGRES_PASSWORD: cadastro
   ports:
    - "5433:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.2
    environment: 
      KEYCLOAK_USER: spark
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"